### ISSUE TITLE
Upgrade to use go vendor standard

### ISSUE THREAD

**Issue by natewoods-wf** [Workiva/frugal#882]
Move godep dependencies to a vendor directory to fall in line with the future of go dependency management.

```
$ godep version
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.8) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
godep v79 (darwin/amd64/go1.8.3)
```

**Comment by kevinsookocheff-wf** [comment]
Closing. Frugal now uses a vendor directory.

**Comment by brandonbodnar-wk** [comment]
I believe this issue should be reopened. 

Under the go vendor standard, vendored libraries should be rooted in the vendor directory like this `vendor/github.com/foo/bar`. See https://golang.org/cmd/go/#hdr-Vendor_Directories

Currently though, Workiva/frugal includes an intermediate src directory like this `vendor/src/github.com/foo/bar`. This inclusion of src prevents go from resolving `github.com/foo/bar` to use the vendored files. 

I tested this locally by running `go test` on the lib/go test files results in a compilation failure due to go using the thrift/lib/go from my $GOPATH and not the vendored files in Workiva/frugal/lib/go.

I attempted a PR to fix this issue, but was having some problems with satisfying dependencies needs for the CI tests (smithy and skynet)

**Comment by brianshannan-wf** [comment]
Yeah, that needs fixed. We've been trying to determine what the impact of moving to glide would be, as we would prefer to do that but worry it might break a lot of consumers. One thing we didn't realize when we did this initially was it will break anyone using frugal in a non-vendored way, as it will try to pull dependencies from two different places (the vendor folder in frugal and the gopath).

**Comment by brianshannan-wf** [comment]
Should be addressed in https://github.com/Workiva/messaging-sdk/pull/580

**Comment by brianshannan-wf** [comment]
Resolved in https://github.com/Workiva/frugal/pull/977
