### ISSUE TITLE
Dart compiler should use `const` rather than `final`

### ISSUE THREAD

**Issue by aurelienmazurie-wk** [Workiva/frugal#974]
Right now the following Frugal code:

```thrift
const string FOO = "foo"
const string BAR = "bar"
```

... is converted into the following Dart code:

```dart
static final String FOO = "foo";
static final String BAR = "bar";
```

... while I would expect the following instead:

```dart
static const String FOO = "foo";
static const String BAR = "bar";
```

This makes `FOO` and `BAR` able to be determined at compile time, allowing their use in switch statements:

```dart
switch (myValue) {
  const FOO:
    ...
  const BAR:
   ...
}
```

Right now `FOO` and `BAR` cannot be used in a switch statement, defeating the purpose of having constant variables.

**Comment by brianshannan-wf** [comment]
This is, unfortunately, something that can't be entirely avoided as we allow structs to be used as constants in frugal IDLs. In dart, for a class to be able to be const it has to have all final properties, which means we can't have setters on classes and inhibits deserialization.

Because of this we use final for all types of constants to prevent confusion for why some constants behave one way and other constants behave in a different way.

**Comment by brianshannan-wf** [comment]
Closing because of the above reason
